### ISSUE TITLE
`MsgUtcTime` implementation of `gps_time` is not checking status flags

### ISSUE THREAD

**Issue by marcomaida94** [swift-nav/libsbp#1385] opened 2023-11-27 14:30 UTC
Hello, I have experienced another inconsistency similar to https://github.com/swift-nav/libsbp/issues/1363

When receiving this message:

```
{"crc":16174,"length":16,"msg_type":259,"msg_name":"MSG_UTC_TIME","payload":"ABQanwC8BwEGAjUuAOmkNQ==","preamble":85,"sender":789,"flags":0,"tow":10426900,"year":1980,"month":1,"day":6,"hours":2,"minutes":53,"seconds":46,"ns":900000000}
```

![image](https://github.com/swift-nav/libsbp/assets/120410627/9e0f0636-1328-4cf3-8602-b70f1e599218)

Seems like [`gps_time()`](https://github.com/swift-nav/libsbp/blob/0bfe6c61bc22e370e50259d1e2e7a4fe1541e277/rust/sbp/src/messages/navigation.rs#L7219) is not checking the appropriate flag.

Thanks!

**Comment by marcomaida94** [comment] 2023-12-15 10:16
Good morning, did you have time to take a look at this? 

Thanks!

**Comment by pcrumley** [comment] 2023-12-19 23:15
Hi @marcomaida94 thank you for bringing this issue to our attention. We haven't had a chance to look at it, but with a quick look it seems very similar to the other `gps_time` status flag issue and hopefully has a similar fix.

We'll let you know when a fix has been implemented.

**Comment by marcomaida94** [comment] 2023-12-21 14:39
Hello, Patrick. I agree with you that it is hopefully quite similar. 

Thanks, will keep an eye on it!
Marco

**Comment by pcrumley** [comment] 2023-12-21 16:55
@marcomaida94 I haven't tried to reproduce this bug yet, but are you using the latest version of libsbp 5.0.4? It looks like this line here: https://github.com/swift-nav/libsbp/blob/5457e5dee70f97bde34ef046cbf6229b2291d74b/rust/sbp/src/messages/navigation.rs#L7229 should solve the issue.

**Comment by marcomaida94** [comment] 2023-12-21 17:12
Hey @pcrumley , we have different versions installed, so it might be that it was recorded not on a fully up-to-date version, though I was expecting this to come from a machine that already integrated https://github.com/swift-nav/libsbp/issues/1363. 

If you think this should be solved on your side, I am ok to close this issue and re-open in case we experience it again.

**Comment by pcrumley** [comment] 2023-12-21 18:12
@marcomaida94 we had a follow-up PR right after that which closed some additional gaps: https://github.com/swift-nav/libsbp/pull/1376

i think this should be fixed. let's close it and then you can re-open if you run into the issue again.

**Closed by pcrumley** 2023-12-21 18:12 UTC
