### ISSUE TITLE
non-iterator of type framer

### ISSUE THREAD

**Issue by DPastl** [swift-nav/libsbp#639] opened 2019-01-25 22:27 UTC
The jck/python3 (5e9dab9)branch installs but fails to run with error:
`TypeError: iter() returned non-iterator of type 'Framer'`

This when running the simple example and using own code.

**Comment by silverjam** [comment] 2019-01-26 02:19
Hello @DPastl -- Python 3 support is still in development and experimental but can you try the `silverjam/py3` and let me know if this solves your problem?

**Comment by DPastl** [comment] 2019-01-29 16:51
Hello @silverjam , thanks for getting back to me!

It now runs, but just throws:

'Host Side Unhandled byte: 0x00`

I also checked that the console appears to work properly and isn't throwing any errors.

I'm installing the module into a fresh 3.6.5 virtual environment by navigating to the python directory in libsbp and running:

`python setup.py install`

Is there something I'm doing wrong perhaps?

**Comment by silverjam** [comment] 2019-01-29 17:05
Firmware version 1.2 is pretty old, you might consider updating as I'm unfamiliar with this error... can you provide more detail? Is there a stack trace, or is this all there is?

Is it possible for you to try Python 2.7?

Also, it would be helpful to understand your intended application, maybe I can suggest an alternate path.

**Comment by DPastl** [comment] 2019-01-29 17:11
Yeah, didn't realize how old they were, looks like some of our boards haven't been used since we initially bought them.  I updated them and still am getting the same error, there is no other information and the terminal is completely filled in a matter of seconds.

What I'd like to do is update our data acquisition software that combines an array of sensors to python 3, since 2 is going out.  Since this is the only instrument running 2.7 it's all that is left before I can upgrade.

**Comment by silverjam** [comment] 2019-01-29 20:19
The `'Host Side Unhandled byte: 0x00'` output looks like it's just a warning.  Can you describe a little more about how your system works so we can try to reproduce?

Official Python 3 support should be forthcoming (in the next couple weeks)-- but this doesn't sound like a Python 3 specific issue anymore.

**Comment by silverjam** [comment] 2019-03-08 18:28
Hi @dpastl, Python 3 support is available in release 2.5.0.  Closing this issue for more, please reopen or contact support@swiftnav.com if you have further issues.

**Closed by silverjam** 2019-03-08 18:28 UTC
